Add TelegramBot
DaniarFF/MedHelp pull request #3
Opened 2024-10-01 17:57 UTC by DaniarFF

1. Подключена библиотека для работы с Telegram ботами - PRTelegramBot (форк Telegram.Bot)
2. Внедрение Dependency Injection (DI)  для оптимизации управления зависимостями.

2024-10-03 09:27 UTC, yaporyvaev requested changes

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Abstractions/ITreatmentTemplateRepository.cs
> +    Task<TreatmentTemplateEntity> Get(User user);
Должен быть только идентификатор пользователя

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Abstractions/ITreatmentTemplateRepository.cs
> +    Task<TreatmentTemplateEntity> Get(User user);
Написано получить все шаблоны, а получаешь только 1 шаблон

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Abstractions/IUserRepository.cs
> +    Task<UserEntity> Get(long tgId);
Что за tgId, символы пожалел?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Abstractions/IUserRepository.cs
> +    /// <param name="tgId"></param>
Описание аргумента отсуствует

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Entities/DiseaseDrugEntity.cs
> +    /// Экземпляр заболевания, связанного с данным препаратом.
Просто "Заболевание"

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Entities/DiseaseEntity.cs
> +  /// Представляет сущность заболевания, содержащую информацию о симптомах, рекомендациях и отличительных признаках.
Слишком подробно и скорее всего никому не нужно

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Entities/DiseaseEntity.cs
> +    public ICollection<DiseaseDrugEntity> DiseaseDrugs { get; set; }
Почему ICollection?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Entities/UserEntity.cs
> +    public string TelegramUserName { get; set; }
Имеет свойство меняться, есть ли смысл хранить неактуальные данные у себя?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Models/MedicalDocument.cs
> +    public string Age { get; set; }
Стринг?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/CreatePDFService.cs
> +  public class CreatePDFService
Плохое название. Зачем конкретизируешь на Create? Да и на PDF не надо конкретизировать. Просто DocumentService можно, вдруг у тебя не только PDF будет и не только создание

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/CreatePDFService.cs
> +    public void CreatePDF(MedicalDocument medDoc)
Нет асинхронных перегрузок? С вводом\выводом лучше рабоать асинхронно

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/CreatePDFService.cs
> +    public static readonly string dest = "example.pdf";
Почему название такое?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/CreatePDFService.cs
> +    private void ManipulatePDF(PdfDocument pdfDoc, iText.Layout.Document doc, MedicalDocument pDFDocument)
Плохое название. В описаниее заполнение PDF, в названии какая-то манипуляция

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/CreatePDFService.cs
> +    private void ManipulatePDF(PdfDocument pdfDoc, iText.Layout.Document doc, MedicalDocument pDFDocument)
Да и в принципе непонятен смысл выделения этого метода

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/CreatePDFService.cs
> +      System.IO.Path.Combine("C:\\Users\\Данияр\\source\\repos\\MedHelpBot\\MedHelp.Core\\Services\\", "FreeSans.ttf"),
Как на моем пк это должно работать? Добавь файл в проект как статику, укажи в свойствах копировать при компиляции и используй нормальный роут

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/CreatePDFService.cs
> +      DateTime dateTime = DateTime.Now;
Огребешь проблем с временными зонами для пользователей из разных регионов

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/CreatePDFService.cs
> +        .SetFont(font).SetFontSize(32)
Каждый метод на своей строчке

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/CreatePDFService.cs
> +      if(pDFDocument.DrugList != null && pDFDocument.DrugList.Count != 0)
pDFDocument.DrugList.Count != 0 можно заменить на pDFDocument.DrugList.Any()

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/CreatePDFService.cs
> +        for (int j = 0; j < pDFDocument.DrugList.Count; j++)
Почему цикл for?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/DiseaseService.cs
> +        .ToList()
Нельзя так делать. Изучай что такое операция Join в SQL и как её использовать в EF

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/DrugService.cs
> +    {
жесть

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/DrugService.cs
> +      List<Drug> drugs = entities.Select(drug => new Drug()
Форматирование страдает. Почему где-то var используешь, а где-то нет?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/UserService.cs
> +      User user = new User();
В чем прекол возвращать юзера, внутри которого ничего нет?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.Core/Services/UserService.cs
> +    private readonly ILogger logger;
Зачем тут логгер?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/AppDbContext.cs
> +    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
Ты же конструкторы снизу пишешь

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/AppDbContext.cs
> +      modelBuilder.ApplyConfiguration(new DrugConfiguration());
Оно же неявно конфиги подтягивать должно

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DiseaseConfiguration.cs
> +      builder.Property(d => d.Name).IsRequired();
Ограничение по символам?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DiseaseConfiguration.cs
> +      builder.Property(d => d.Id).IsRequired();
Первичный ключ всегда обязателен

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DiseaseConfiguration.cs
> +  public class DiseaseConfiguration : IEntityTypeConfiguration<DiseaseEntity>
Что по индексам?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DrugGroupConfiguration.cs
> +      builder.Property(gd => gd.Name).IsRequired();
Длина?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/DiseaseRepository.cs
> +        .FirstOrDefault(x => x.Name == drugName);
Поиск кейс сенсетив?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/DiseaseRepository.cs
> +      try
Зачем?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/DiseaseRepository.cs
> +        Console.WriteLine(ex.Message);
Нельзя использовать консоль здесь

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/DiseaseRepository.cs
> +    private readonly ILogger logger;
Зачем логгер?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/DiseaseRepository.cs
> +    public DiseaseRepository(AppDbContext applicationDbContex, ILogger<DiseaseRepository> logger)
Конструктор внизу файла

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/DrugRepository.cs
> +    public async Task<IQueryable<DrugEntity>> Get(string drugName)
Чет стремный метод какой-то

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/MedHelp.DBase.csproj
> +    <PackageReference Include="NEST" Version="7.17.5" />
Зачем нест?

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/MedHelp.DBase.csproj
> +    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
Неоч помню, но на линуксе вроде не работает

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/UserRepository.cs
> +        Console.WriteLine(ex.Message);
!!!!

2024-10-03 09:27 UTC, yaporyvaev commented on MedHelp.DBase/UserRepository.cs
> +        logger.LogError(ex, "Ошибка обновления информации пользователя");
Как будто неоч полезно

2024-10-04 15:41 UTC, DaniarFF commented on MedHelp.Core/Models/MedicalDocument.cs
> +    public string Age { get; set; }
Да, не имеет большую значимость тип, так как с помощью него формируется ток пдфка и проще написать 2 года или 5 лет, а не обрабатывать лишний раз введенное значение

2024-10-04 15:49 UTC, DaniarFF commented on MedHelp.Core/Services/CreatePDFService.cs
> +    public void CreatePDF(MedicalDocument medDoc)
Библиотека не поддерживает асинхронные методы, я загуглил шо можно сделать через Task.Run(), но стоит ли?

2024-10-04 16:42 UTC, DaniarFF commented on MedHelp.DBase/DrugRepository.cs
> +    public async Task<IQueryable<DrugEntity>> Get(string drugName)
поч?

2024-10-10 07:46 UTC, DaniarFF commented on MedHelp.Core/Services/CreatePDFService.cs
> +    private void ManipulatePDF(PdfDocument pdfDoc, iText.Layout.Document doc, MedicalDocument pDFDocument)
Название метода позаимствована с документации библиотеки, на самом деле больше не приходят названий в голову)

2024-11-10 21:34 UTC, yaporyvaev approved these changes

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.Core/Abstractions/IDrugRepository.cs
> +    Task Add(DrugEntity drugEntity);
Аргумент можно просто drug назвать

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.Core/Abstractions/IUserRepository.cs
> +    Task Delete(UserEntity entity);
Везде по айдишнику удаляшеь, почему тут по сущности?

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.Core/Entities/DiseaseDrugEntity.cs
> +  /// Представляет связь между <see cref="DrugEntity"/> и <see cref="DiseaseEntity"/>
Не нужны вводные слова типа "представляет", заметил что везде пишешь такое

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.Core/Entities/DiseaseEntity.cs
> +    public ICollection<DiseaseDrugEntity> DiseaseDrugs { get; set; }
И че зарезолвил. Почему ICollection?

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.Core/Models/MedicalDocument.cs
> +    public string Age { get; set; }
> Да, не имеет большую значимость тип, так как с помощью него формируется ток пдфка и проще написать 2 года или 5 лет, а не обрабатывать лишний раз введенное значение

Из названия и комментария не очевидно что там будет "5 лет", а не просто цифра "5"

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.Core/Services/DocumentService.cs
> +  public class DocumentService
Поч тут без интерфейса?

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.Core/Services/DocumentService.cs
> +    public static readonly string dest = "recipe.pdf";
хз юзлесс какой-то, но можно оставить

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.Core/Services/UserService.cs
> +        Id = userEntity.Id,
Форматирование

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/AppDbContext.cs
> +      modelBuilder.ApplyConfiguration(new DrugConfiguration());
Чёт всё-таки я не помню что надо это явно указывать

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DiseaseConfiguration.cs
> +  public class DiseaseConfiguration : IEntityTypeConfiguration<DiseaseEntity>
Нужны индексы

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DiseaseConfiguration.cs
> +  public class DiseaseConfiguration : IEntityTypeConfiguration<DiseaseEntity>
Во все таблицы, где они нужны

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DiseaseConfiguration.cs
> +  public class DiseaseConfiguration : IEntityTypeConfiguration<DiseaseEntity>
А где они нужны -- тебе надо самому решить, контрольная работа

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DiseaseDrugConfiguration.cs
> +      builder.Property(dd => dd.Peculiarity).HasMaxLength(200).IsRequired(false);
IsRequired по дефолту фолс

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DrugConfiguration.cs
> +      builder.Property(c => c.Name).HasMaxLength(50).IsRequired();
Не надо оч сильно жалеть символы, может не хватить на хачевские имена мб

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DrugConfiguration.cs
> +      builder.Property(c => c.Name).HasMaxLength(50).IsRequired();
Можно не править

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/DrugGroupConfiguration.cs
> +      builder.Property(gd => gd.Name).IsRequired().HasMaxLength(50);
Также

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/Configuration/TreatmentTemplateConfiguration.cs
> +      builder.Property(tt => tt.TemplateName).HasMaxLength(20);
Надеюсь ты валидацию на фронте сделал на это количество

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/Entry.cs
> +    private static readonly Action<DbContextOptionsBuilder> DefaultOptionsAction = (_) => { };
Можешь удалить, всё равно не будешь никогда использовать

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/UserRepository.cs
> +    public async Task<UserEntity> Get(long tgId)
Не жалей букв, пиши нормаьно

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.DBase/UserRepository.cs
> +      throw new NotImplementedException();
Ну и зачем

2024-11-10 21:34 UTC, yaporyvaev commented on MedHelp.TelegramBot/appsettings.json
> +{
че прикалываешься)))

2024-11-11 15:52 UTC, DaniarFF commented on MedHelp.Core/Entities/DiseaseEntity.cs
> +    public ICollection<DiseaseDrugEntity> DiseaseDrugs { get; set; }
Исправил

2024-11-11 16:50 UTC, merged